name: server_tutorial
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
dependencies:
  - aioconsole=0.8.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.6.0
  - openssl=3.0.17
  - packaging=25.0
  - parso=0.8.4
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - pywin32=308
  - pyzmq=26.2.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
